---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Analyzer

<!-- badges: start -->
<!-- badges: end -->

The goal of Analyzer is to help with text analyzing

## Installation

You can install the development version of Analyzer from [GitHub](https://github.com/itmeandy/Analyzer) with:

``` r
# install.packages("devtools")
devtools::install_github("itmeandy/Analyzer")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(Analyzer)
## basic example code
text <- "Hello there, this shall be Andys simple example!"
cleaned_text <- clean_text(text, TRUE, TRUE, TRUE)
print(cleaned_text)
Information <- word_amount_ngrams(cleaned_text, 2)
print(Information)
count_shall <- check_word_frequency(Information, "shall")
print(count_shall)
```

